### ISSUE TITLE
Not compatible with Node.js 6

### ISSUE THREAD

**Issue by piranna** [avz/node-mkfifo#4]
When trying to install `mkfifo` with Node.js 6.0.0-pre there are some errors related to v8. You should update the code to use `nan` module to make it agnostic to the Node.js version being used.

**Comment by avz** [comment]
I just checked the module with `v6.0.0-nightly20160307449684752c` and all works fine. Can you tell me your system information and version of `node`?

**Comment by piranna** [comment]
I've tried it on OSX, maybe that's the reason? I compiled the code from git
master, how did you get a nightly build?

**Comment by piranna** [comment]
Thank you :-)
