### ISSUE TITLE
Add async version

### ISSUE THREAD

**Issue by piranna** [avz/node-mkfifo#5]
Add async version of the `mkfifosync()` function.

**Comment by hhamilto** [comment]
@avz would you accept a PR for this?

**Comment by piranna** [comment]
I would definitely interested on that :-)

**Comment by avz** [comment]
@hhamilto of course, I'll be glad to accept the PR 👍

**Comment by avz** [comment]
I release a new version 1.2.5 with asynchronous mkfifo()
