### ISSUE TITLE
Does not work on Node 11

### ISSUE THREAD

**Issue by computersrmyfriends** [avz/node-mkfifo#9]
Unable to install on Node 11

`/root/.node-gyp/11.0.0/include/node/v8.h:2571:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/11.0.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
mkfifo.target.mk:101: recipe for target 'Release/obj.target/mkfifo/src/mkfifo.o' failed
make: *** [Release/obj.target/mkfifo/src/mkfifo.o] Error 1
make: Leaving directory '/root/node_modules/mkfifo/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root//node_modules/mkfifo
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok`

**Comment by avz** [comment]
I'm not very fast, so only now I was able to release version 2.0.0 with N-API support.
This version should work on all modern nodejs versions.

So if it is still relevant, then use the new version.
